name: This is a test yaml
on: 
  pull_request:
     branches:
        - 'main'

jobs:
   build:
      runs-on: ubuntu-latest
      
      steps: 
         - name: checkout code
           uses: actions/checkout@v2
